//inventory <-> order <-> payment

syntax = "proto3";

package order.v1;

import "google/protobuf/timestamp.proto";
import "common/v1/common.proto";

service OrderService {

rpc PlaceOrder(PlaceOrderRequest) returns (PlaceOrderResponse);

rpc GetOrder(GetOrderRequest) returns (Order);

rpc WatchOrderStatus(WatchOrderStatusRequest) returns (stream OrderStatusUpdate);

rpc CancelOrder(CancelOrderRequest) returns (CancelOrderResponse);

}

message Order {
    string order_id = 1;
    string customer_id = 2;
    repeated OrderItem items = 3;
    OrderStatus status = 4;
    common.v1.Money total_amount = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}

message OrderItem {
    string product_id = 1;
    int32 quantity = 2;
    common.v1.Money unit_price = 3;
}

enum OrderStatus {
    ORDER_STATUS_UNSPECIFIED = 1;
    ORDER_STATUS_PENDING = 2;
    ORDER_STATUS_STOCK_RESERVED = 3;
    ORDER_STATUS_PAYMENT_PROCESSING = 4;
    ORDER_STATUS_CONFIRMED = 5;
    ORDER_STATUS_FAILED = 6;
    ORDER_STATUS_CANCELLED = 7;
}
message PlaceOrderRequest {
        string customer_id = 1;
        repeated OrderItem items = 2;
} 

message PlaceOrderResponse {
    string order_id = 1;
    OrderStatus status = 2;
    string failure_reason = 3; // only populated if order status is ORDER_STATUS_FAILED
}

message GetOrderRequest {
string order_id = 1;
}
message WatchOrderStatusRequest {
    string order_id = 1;
}

message OrderStatusUpdate {
    string order_id = 1;
    OrderSetatus status = 2;
    google.protobuf.Timestamp updated_at = 3;
    string note = 4;
}
message CancelOrderRequest {
    string order_id = 1;
    string reason = 2;
}

message CancelOrderResponse {
    string order_id = 1;
    OrderStatus status = 2;
}